version: "3.8"
services:
  luckynumber:
    build: ./LuckyNumberGenerator
    ports:
      - '5000:80'

  webapi:
    build: ./WebApi
    ports:
      - '5001:80'
    environment:
      - LuckyNumberService:ApiUrl=http://luckynumber:80/
    depends_on:
      - luckynumber

  frontend:
    build: ./Angular
    ports:
      - '4200:80'
    environment:
      - API_URL=http://localhost:5001/
    depends_on:
      - webapi